### ISSUE TITLE
"Ecowitt Weather Station" repository do not appear in HACS Integrations Click "+" 

### ISSUE THREAD

**Issue by j-hipe** [PoppyPop/homeassistant_ecowitt#57]
Following the instructions:
1. Go to HACS -> Integrations -> Click "+"
2. Search for "Ecowitt Weather Station" repository and add to HACS
But the integration do not appear in the search.

HA Core 2022.4.5
Any idea?

**Comment by Eonsim** [comment]
Try force refreshing HA, it appeared for me after I did that.

**Comment by j-hipe** [comment]
This don't work.
Integration is also not listed in the HA integration list:
https://www.home-assistant.io/integrations/#all

**Comment by tbgoose** [comment]
Same issue here. Have tried installing manually and via HACS with this git as the repository.

Have restarted HA multiple times and cleared cache. The integration does not show up in search after 

HA Core 2022.5.4

**Comment by DoerakkerHA** [comment]
> This don't work. Integration is also not listed in the HA integration list: https://www.home-assistant.io/integrations/#all

hacs integrations are not listed in the official HA docs (as far as I know) 
https://github.com/garbled1/homeassistant_ecowitt

**Comment by PoppyPop** [comment]
Sorry, i will archive the repository
