### ISSUE TITLE
Unhandelled sensors: Ecowitt WittBoy GW2001

### ISSUE THREAD

**Issue by Eonsim** [PoppyPop/homeassistant_ecowitt#58]
Hi,

It looks like the integration doesn't currently handle all the sensors available from the GW2001.
Please let me know if there are any additional details you need.

mrain_piezo yrain_piezo would be the piezo electric rainfall sensors the system uses.
ws90cap_volt is the supercapaciter voltage (linked to the solar panel I assume).
wh90batt is the battery voltage.

This error originated from a custom integration.

Logger: custom_components.ecowitt
Source: custom_components/ecowitt/__init__.py:288
Integration: Ecowitt Weather Station (documentation, issues)
First occurred: April 21, 2022, 7:32:14 PM (9802 occurrences)
Last logged: 10:34:38 AM

Unhandled sensor type mrain_piezo value 0.004, file a PR.
Unhandled sensor type yrain_piezo value 0.004, file a PR.
Unhandled sensor type ws90cap_volt value 2.0, file a PR.
Unhandled sensor type ws90_ver value 117, file a PR.
Unhandled sensor type wh90batt value 2.52, file a PR.

**Comment by PoppyPop** [comment]
Sorry, i will archive the repository
