### ISSUE TITLE
No passkey, cannot set unique id.

### ISSUE THREAD

**Issue by githubDiversity** [PoppyPop/homeassistant_ecowitt#59]
I've got the following errors in the HA log.
I found those errors after the Ecowitt card did not show up in HA integrations.

---------------
This error originated from a custom integration.

Logger: custom_components.ecowitt
Source: custom_components/ecowitt/__init__.py:243
Integration: Ecowitt Weather Station (documentation, issues)
First occurred: 5:06:23 PM (211 occurrences)
Last logged: 7:08:15 PM

No passkey, cannot set unique id.
---------------

Any idea where I can look for a cause? The WA View app does not have a field to set a pass key if the problem comes from there.

**Comment by PoppyPop** [comment]
Sorry, i will archive the repository
